drivers: Fix missing asm/io.h include in sensors/sensors_ssc.c
Currently build fails with the following errors

../drivers/sensors/sensors_ssc.c:61:12: error: implicit declaration of function ‘__raw_readl’; did you mean ‘__up_read’? [-Werror=implicit-function-declaration]
../drivers/sensors/sensors_ssc.c:275:23: error: implicit declaration of function ‘ioremap’ [-Werror=implicit-function-declaration]
../drivers/sensors/sensors_ssc.c:275:21: warning: assignment makes pointer from integer without a cast [-Wint-conversion]

Fix by including asm/io.h, which contains definitions or prototypes
for these macros or functions.
Signed-off-by: Harsh Shandilya <harsh@prjkt.io>